name: Content Submission
description: Submit setups, mods, guides, or other sim racing content
title: "[CATEGORY] Your Content Title"
labels: ["content-submission", "needs-review"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Content Category
      description: What type of content are you submitting?
      options:
        - Car Setup
        - Mod/App
        - Guide/Tutorial
        - 3D Print File
        - Livery/Skin
        - Track
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: game
    attributes:
      label: Game/Simulator
      description: Which sim is this for?
      options:
        - Assetto Corsa
        - Assetto Corsa Competizione
        - rFactor 2
        - iRacing
        - Automobilista 2
        - F1 Series
        - Dirt Rally
        - Other
    validations:
      required: true
      
  - type: input
    id: author
    attributes:
      label: Author/Creator
      description: Your name or username
      placeholder: "e.g., RacingPro42"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of your content
      placeholder: "Describe your setup, mod, guide, etc. Include any special instructions or requirements."
    validations:
      required: true
      
  - type: textarea
    id: installation
    attributes:
      label: Installation Instructions
      description: How to install/use your content
      placeholder: "Step-by-step instructions for users"
      
  - type: input
    id: car
    attributes:
      label: Car/Vehicle (if applicable)
      description: Specific car this content is for
      placeholder: "e.g., Mercedes AMG GT3"
      
  - type: input
    id: track
    attributes:
      label: Track (if applicable)
      description: Specific track this content is for
      placeholder: "e.g., Silverstone GP"
      
  - type: textarea
    id: files
    attributes:
      label: Files
      description: List the files you're uploading and drag & drop them below
      placeholder: "- setup.json\n- readme.txt\n- screenshot.jpg"
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this content, you agree to
      options:
        - label: I own the rights to this content or have permission to share it
          required: true
        - label: This content is safe and does not contain malicious code
          required: true
        - label: I allow this content to be freely shared with the community
          required: true
