name = "srm-api"
main = "src/index.ts"
compatibility_date = "2024-04-03"

kv_namespaces = [
  { binding = "SRM_COUNTS", id = "3e9378b112424577b8b855b7b0b35ffb" },
  { binding = "SRM_RATELIMIT", id = "83150df80d6c4cda8ba890836b129a79" }
]

[vars]
GH_OWNER = "SimRaceMarket"        # <— your org/user
GH_REPO  = "SRM-UGC"              # <— repo with approved.json
MAX_FILE_BYTES = 10000000
ALLOWED_ORIGINS = "https://www.simracemarket.com,https://simracemarket.com,https://*.framer.app"
